(defpackage captcha
  (:use :common-lisp))

(defparameter *current-expr* nil
  "Latest expression generated by `generate-question'.")

(defconstant +MAX-NUMBER+ 10
  "The upper limit of number for arithmetic calculation.")

(defconstant +MIN-NUMBER+ 1
  "The lower limit of number for arithmetic calculation.")

(defparameter *arith-ops*  '(+ - * /)
  "The number of available arithmetic operations.")

(defparameter *nouns* '("apples" "oranges" "avocados" "bananas" "watermelons" "pumpkins"
                        "strawberries" "blueberries" "guavas" "mangos" "pineapples"))
(defparameter *pronouns* '("of them" "them all"))
(defparameter *first-operand-verbs* '("start with" "having bought" "having" "acquired" "given" "there are" "you have"))
(defparameter *plus-verbs* '("received another" "picked up" "and you was gifted"))
(defparameter *minus-verbs* '("dropped" "ate" "gave away"))
(defparameter *time-verbs* '("times" "multiplied by"))
(defparameter *divide-verbs* '("divided by"))

(defun generate-arith-expression ()
  (let* ((number1  (1+ (random +MAX-NUMBER+)))
         (number2  (1+ (random +MAX-NUMBER+)))
         (op (nth  (random (length *arith-ops*)) *arith-ops*)))
    (append (list op)
            (case op
              ('- (if (> number1 number2) (list number1 number2) (list number2 number1)))
              ('/
               (setf number1 (* number2 (1+ (random +MAX-NUMBER+))))
               (list number1 number2))
              (otherwise (list number1 number2))))))

(defun calculate (expr)
  "Calculate expression generated from generate-arith-expr."
  (apply (car expr) (cdr expr)))

(defun answer-correct-p (ans expr)
  "Check whether user answer matched arithmetic expression."
  (if  (= ans (calculate expr))
       "T"
       "F"))

(defun op->verb (op)
  (case op
    ('+ (nth (random (length *plus-verbs*)) *plus-verbs*))
    ('- (nth (random (length *minus-verbs*)) *minus-verbs*))
    ('* (nth (random (length *time-verbs*)) *time-verbs*))
    ('/ (nth (random (length *divide-verbs*)) *divide-verbs*))
    (otherwise (error "Operator not supported."))))

(defun op->end-question (op)
  (case op
    ('+ "how many do you have in total?")
    ('- "how many are left?")
    ('* "what is the result?")
    ('/ "what is the result?")
    (otherwise (error "Operator not supported."))))

(defun expression->question (expr)
  "Turn an aritmetic expression into a question."
  (let* ((op (car expr))
         (number1 (cadr expr))
         (number2 (caddr expr))
         (pronoun "of them")
         (start-verb (nth (random (length *first-operand-verbs*)) *first-operand-verbs*))
         (object (nth (random (length *nouns*)) *nouns*))
         (op-verb (op->verb op))
         (end-question (op->end-question op)))
    (format nil "~A ~d ~A, ~A ~d ~A, ~a" start-verb number1 object op-verb number2 pronoun end-question)))

(defun generate-question ()
  (setf *current-expr* (generate-arith-expression))
  (expression->question *current-expr*))

(defun start-echo-server (port)
  "Listening on a port for a message, and response the with a question."
  (usocket:with-socket-listener (socket "127.0.0.1" port)
    (loop
      (usocket:wait-for-input socket)
      (usocket:with-connected-socket (connection (usocket:socket-accept socket))
        (let ((msg (read-line (usocket:socket-stream connection))))
          (print msg)
          (cond
            ((string-equal msg "GET")
             (let ((q (generate-question)))
               (print q)
               (format (usocket:socket-stream connection) q)
               (force-output (usocket:socket-stream connection))))
            (t
             (format (usocket:socket-stream connection)
                     (answer-correct-p (parse-integer msg) *current-expr*))
             (force-output (usocket:socket-stream connection)))))))))
